language: ruby

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1

cache: bundler

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4_with_sprockets_2.gemfile
  - gemfiles/rails_4_with_sprockets_3.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.gemfile
