language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3

cache: bundler

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4_with_sprockets_2.gemfile
  - gemfiles/rails_4_with_sprockets_3.gemfile
  - gemfiles/rails_5.gemfile
